name: Invsee
version: '1.0'
main: de.Main.invsee.Main
api-version: '1.21'
authors: [ nospighost, Fabian260108 ]
description: Ein Job Plugin, Perfekt für Citybuild Server
commands:
  invsee:
    description: Zeigt oder bearbeitet das Inventar eines Spielers.
    usage: /invsee <Spieler>
    permission: be.invsee
    permission-message: "§cDu hast keine Berechtigung, diesen Befehl zu verwenden."
  invseetoggle:
    description: Schalte an und aus, das andere Leute in dein Inv gucken können (Team ausgeschlossen)
    usage: /invseetoggle
    permission: be.invsee.toggle

permissions:
  be.invsee.supporter:
    description: Erlaubt das Ansehen von Inventaren normaler Spieler.
    default: false
  be.invsee:
    description: Erlaubt das Ansehen von Inventaren normalen Spieler.
    default: false
  be.invsee.mod:
    description: Erlaubt das Ansehen und Bearbeiten von Inventaren normaler Spieler und Supporter.
    default: false
  be.invsee.teamlead:
    description: Vollzugriff auf Inventare, außer von Admins.
    default: false
  be.invsee.admin:
    description: Vollzugriff auf alle Inventare.
    default: false
  be.invsee.denyview:
    description: Verbietet normalen Usern das Gucken in Fremde Inventare
    default: false
  be.invsee.bypass:
    description: Ignoriert Sichtbarkeits-Toggle.
    default: false
  be.invsee.toggle:
    description: Schalte an und aus, das andere Leute in dein Inv gucken können (Team ausgeschlossen)
    default: false